permalink: /:categories/:year/:month/:day/:title 

exclude: ["README.md"]
pygments: true

title : "Amanda Morales"
tagline: "Psicóloga y Bailarina"
description: "Esta es una breve descripción sobre mi"
image: "/img/meta-img.jpg"

author :
  name : "Amanda Morales"
  email : "amanmorales@gmail.com"
  page: "http://dreija.github.io"
  services:
    twitter: edwrodrig

production_url : http://dreija.github.io
google_tracking_id : "UA-49580762-2"

type:
  name: "normal"

sharing:
  style: "native"
  services:
    - "facebook"
    - "twitter"
    - "google-plus"
    - "pinterest"

markdown: kramdown
